### PR TITLE
Renamed  kurtosis.mod file to the new kurtosis.yml  file format

### PR DESCRIPTION
**Pull request by leoporoli**

### CODE REVIEW

**Comment by leoporoli** [comment]
@gbouv now it's failing because we have to release the new CLI version, I'll let you now when it's ready

**Review by h4ck3rk3y — COMMENTED** [review]
Looks good to me, can this be changed in eth2-module as well.

**Review by h4ck3rk3y — APPROVED** [review]
merge when CI runs

**Comment by gbouv** [comment]
I had to do it in https://github.com/kurtosis-tech/datastore-army-module/pull/41 otherwise tests were failing

**Pull request closed without merging**
